name: CI Pipeline

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_api:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out your code from the repo
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Set up Python 3.9 (Same as your Dockerfile)
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 3. Install Dependencies
    # We install pytest and httpx for testing, plus your app requirements
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest httpx
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # 4. Run Tests
    # This runs the test.py file you created
    - name: Run Tests
      run: |
        pytest tests/test.py